# Generated by Django 5.1.6 on 2025-02-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('image_name', models.CharField(max_length=255)),
                ('view_name', models.CharField(max_length=255)),
                ('allowed_groups', models.ManyToManyField(related_name='dashboards', to='auth.group')),
            ],
        ),
    ]
