# Generated by Django 5.1.6 on 2025-02-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='image_name',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dashboards/'),
        ),
    ]
