# Generated by Django 5.1.6 on 2025-02-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_remove_dashboard_image_name_dashboard_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
