# Generated by Django 5.1.6 on 2025-02-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_dashboard_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Whether the dashboard is enabled or not'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='view_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
