# Generated by Django 5.1.6 on 2025-02-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_alter_dashboard_enabled_alter_dashboard_view_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='view_name',
            field=models.CharField(blank=True, help_text='Name of the view that renders the dashboard (stored in templates/dashboards, if not provided, a view that matches the slug is expected)', max_length=255, null=True),
        ),
    ]
