version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: baddy_postgres
    restart: always
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: password
      POSTGRES_DB: baddy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  baddy:
    image: baddy
    container_name: baddy_app
    restart: no
    environment:
      DJANGO_ENV: production
      DB_USER: django
      DB_PASSWORD: password
      DB_NAME: baddy
      DB_HOST: postgres
      DB_PORT: 5432
      DEBUG: True
      SECRET_KEY: django-insecure-1nze18c1fv*tq2%0#z%bo4uagwis5h27sco#w9efukqoi(__iz
      CSRF_HOSTS: http://localhost:8000
      ADMIN_USERNAME: admin
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: password

    depends_on:
      - postgres
    ports:
      - "8000:80"

volumes:
  postgres_data:

